<?php

namespace MainBundle\Repository;

/**
 * InscrireFormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscrireFormationRepository extends \Doctrine\ORM\EntityRepository
{
}
