<?php

namespace MainBundle\Repository;

/**
 * ParticipersfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipersfRepository extends \Doctrine\ORM\EntityRepository
{
}
