<?php

namespace MainBundle\Repository;

/**
 * responseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class responseRepository extends \Doctrine\ORM\EntityRepository
{
}
