<?php

namespace MainBundle\Repository;

/**
 * Session_FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Session_FormationRepository extends \Doctrine\ORM\EntityRepository
{
}
