<?php

namespace MainBundle\Repository;

/**
 * Test_ChapitreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Test_ChapitreRepository extends \Doctrine\ORM\EntityRepository
{
}
