sonata_block:
    default_contexts: [sonata_page_bundle]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

services:
    main.admin.formation:
        class: MainBundle\Admin\FormationAdmin
        arguments: [~, MainBundle\Entity\Formation, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Formation }
        public: true

    main.admin.apprenant:
        class: MainBundle\Admin\ApprenantAdmin
        arguments: [~, MainBundle\Entity\Apprenant, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Apprenant }
        public: true

    main.admin.session.formation:
        class: MainBundle\Admin\Session_FormationAdmin
        arguments: [~, MainBundle\Entity\Session_Formation, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Session_Formation }
        public: true
