main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }

layout:
    path:     /layout
    defaults: { _controller: MainBundle:Layout:layout }

index:
    path:     /index
    defaults: { _controller: MainBundle:Layout:indexelearning}

session:
    path:     /sessionformation
    defaults: { _controller: MainBundle:Sessionformation:afficher}

presentation:
    path:     /presentation
    defaults: { _controller: MainBundle:Layout:presentation }

contacter:
    path:     /contacter
    defaults: { _controller: MainBundle:Contact:contacter}
catalogue:
    path:     /catalogue
    defaults: { _controller: MainBundle:Formation:catalogue}

gallerie:
    path:     /gallerie
    defaults: { _controller: MainBundle:Gallerie:affichergallerie}

inscrire:
    path:     /inscrire
    defaults: { _controller: MainBundle:Inscrireformation:inscrire}

formation:
    path:     /formation/{id}
    defaults: { _controller: MainBundle:Formation:afficher}
cours:
    path:     /cours
    defaults: { _controller: MainBundle:Cours:ajouter}
modifiercours:
    path: /modifiercours/{id}
    defaults: { _controller: MainBundle:Cours:editerCours}
affichercourss:
    path:     /affichercourss/{id}
    defaults: { _controller: MainBundle:Affichercours:affichercours}
affichercourssapprenant:
    path:     /affichercourssapprenant/{id}
    defaults: { _controller: MainBundle:Affichercoursapprenant:affichercoursapprenant}
inscription:
    path:     /inscription/{id}
    defaults: { _controller: MainBundle:Sessionformation:inscription}
apprenants:
    path:     /apprenants/{id}
    defaults: { _controller: MainBundle:Sessionformation:display}
notif:
    path:     /contact/notif
    defaults: { _controller: MainBundle:Contact:countMsg}
    options:
        expose: true}
contactapprenant:
    path:     /contactapprenant
    defaults: { _controller: MainBundle:Contactapprenant:contactapprenant}
contactformateur:
    path:     /contactformateur
    defaults: { _controller: MainBundle:Contactformateur:contactformateur}
mysession:
    path:     /mysession
    defaults: { _controller: MainBundle:Sessionformation:display}