<?php
/**
 * Created by PhpStorm.
 * User: sabine
 * Date: 30/05/2018
 * Time: 11:07
 */

namespace MainBundle\Controller;

use MainBundle\Entity\Cours;
use MainBundle\Form\CoursType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;


class CoursController extends Controller
{
    public function ajouterAction(Request $request)
    {

        $cours = new Cours();
        $form = $this->createForm(CoursType::class,$cours);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {


            $file = $cours->getFile();

            $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();

            // moves the file to the directory where brochures are stored
            $file->move(
                $this->getParameter('cour_directory'),
                $fileName
            );

            // updates the 'brochure' property to store the PDF file name
            // instead of its contents
            $cours->setCours($fileName);

            // ... persist the $product variable or any other work
            $em = $this->getDoctrine()->getManager();
            $em->persist($cours);

            $em->flush();
            return $this->redirect($this->generateUrl('cours'));
        }


        return $this->render('MainBundle:Cours:cours.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    public  function affichercoursAction()
    {

        $em = $this->getDoctrine()->getEntityManager();

        $form = $em->getRepository('MainBundle:Cours')->findAll();


        return $this->render('MainBundle:Cours:listecours.html.twig', array(
            'form' => $form,
        ));
    }
    public function editerCoursAction(Request $request, $id) {

        $cours= $this->getDoctrine()
            ->getEntityManager()
            ->getRepository('MainBundle:Cours')
            ->find($id);
        $form = $this->createForm(CoursType::class
            , $cours);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $file = $cours->getFile();

            $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();

            // moves the file to the directory where brochures are stored
            $file->move(
                $this->getParameter('cour_directory'),
                $fileName
            );

            // updates the 'brochure' property to store the PDF file name
            // instead of its contents
            $cours->setCours($fileName);

            $em = $this->getDoctrine()->getManager();
            $em->persist($cours);
            $em->flush();
        }
        return $this->render('MainBundle:Cours:cours.html.twig', array(
            'form' => $form->createView(),
        ));

    }



}




